### ISSUE TITLE
[Issue] Trash Pack doesn't work

### ISSUE THREAD

**Issue by 0swin** [Sefiraat/DankTech#15]
## Description (Mandatory)
Trash Pack doesn't work

## What caused the issue, what steps led up to the issue (Mandatory)
I tried both Trash Pack t1 and t2, with Enderman Head and Ender Pearl in the filter slots. When I pick up Ender Pearls and Heads at my Enderman farm, they go in my inventory.

## Log of error, if applicable
Latest logs too long too publish on pastebin, but tl;dr, DankTech doesnt produce any error while it loads, seems to load correcty, and doesnt send anything in console after server has finished loading 

## Server Type and verison (Spigot/Paper etc.)
paper-1.17.1-107.jar
Plugins (34): AutomatedCrafting, Brewery, ChestTerminal, ColoredEnderChests, CrazyEnchantments, DankTech, DriveBackupV2, DyedBackpacks, DynaTech, dynmap, EcoPower, EquivalencyTech, ExperienceTome, FastLeafDecay, FluffyMachines, GSit, LiteXpansion, LuckPerms, MendingEnchant, Multiverse-Core, ProtocolLib, SetHomes, SFCalc, SimpleStorage, SimpleUtils, SkinsRestorer, Slimefun, SlimefunOreChunks, SlimeTinker, SlimyTreeTaps, SoundMuffler, SpawnerSilk, ViaBackwards, ViaVersion

## Minecraft version
1.17.1

**Comment by Sefiraat** [comment]
Thanks, I have a fix for this luckily - it should be out tomorrow :)

**Comment by Sefiraat** [comment]
Fixed and pushed in 1.2.9 ty, sorry for the wait!

**Comment by 0swin** [comment]
Sorry to reopen this,
Does this fix affect all Trash Packs or should I craft a new one ? It still isn't working for me 😅

**Comment by 0swin** [comment]
Here is a demonstration : 
https://youtu.be/TR5enJWPtDk
